### This was done on google colab

In [1]:
!pip install sentence-transformers faiss-cpu tensorflow-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.3/31.3 MB 72.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.8/251.8 MB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 120.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 113.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 118.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 95.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 57.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 17.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20

In [2]:
import pandas as pd

pd.set_option('display.max_colwidth', 100)
df= pd.read_csv('sample_text.csv')
df.shape

(8, 2)

In [16]:
df.head(9)

text  \
0                                        Meditation and yoga can improve mental health   
1                       Fruits, whole grains and vegetables can control blood pressure   
2                                     These are the latest fashion trends of this week   
3                                   Vibrant colour jeans for male are becoming a trend   
4                                                    The concert starts at 7PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [3]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer('all-mpnet-base-v2')
vectors= encoder.encode(df.text)
vectors.shape

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

(8, 768)

In [5]:
dim= vectors.shape[1]
dim

#every vector has these many dimensions

768

In [6]:
import faiss

index= faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss_avx512.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7d41e8e0b7e0> >

In [7]:
index.add(vectors)

In [9]:
search_query= "I want to buy a Polo t-shirt"

vec= encoder.encode(search_query)
vec.shape

(768,)

In [11]:
vec

array([ 1.03882840e-02,  2.78685410e-02, -1.18618114e-02,  1.81327034e-02,
        1.21984573e-03, -1.42995603e-02,  1.96229611e-02,  2.07198001e-02,
       -2.23660674e-02,  4.75626737e-02,  1.77976526e-02, -8.00332800e-03,
        2.53419168e-02,  5.26148528e-02,  8.44946038e-03, -1.63943805e-02,
        1.02661196e-02, -2.74856500e-02,  8.37067440e-02, -1.52885374e-02,
        1.67682637e-02, -3.97138251e-03, -2.74348874e-02,  5.02092130e-02,
       -8.36519711e-03, -4.74075042e-02,  2.36915872e-02, -1.01185953e-02,
       -2.82840449e-02,  7.94265792e-03,  4.21435609e-02, -4.19379678e-03,
       -1.91232786e-02, -3.12785469e-02,  1.24685096e-06, -1.04428604e-02,
       -2.19971444e-02, -8.66928250e-02, -1.88502751e-03, -2.54772119e-02,
       -9.72970109e-03,  7.93310180e-02, -3.55963036e-02, -3.05334688e-04,
       -1.12392278e-02, -3.88932340e-02,  5.49314320e-02,  1.35207996e-01,
       -8.19147304e-02,  1.18784690e-02, -9.01846774e-03,  1.92544591e-02,
       -2.82723811e-02, -

In [10]:
import numpy as np

svec= np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [12]:
svec

array([[ 1.03882840e-02,  2.78685410e-02, -1.18618114e-02,
         1.81327034e-02,  1.21984573e-03, -1.42995603e-02,
         1.96229611e-02,  2.07198001e-02, -2.23660674e-02,
         4.75626737e-02,  1.77976526e-02, -8.00332800e-03,
         2.53419168e-02,  5.26148528e-02,  8.44946038e-03,
        -1.63943805e-02,  1.02661196e-02, -2.74856500e-02,
         8.37067440e-02, -1.52885374e-02,  1.67682637e-02,
        -3.97138251e-03, -2.74348874e-02,  5.02092130e-02,
        -8.36519711e-03, -4.74075042e-02,  2.36915872e-02,
        -1.01185953e-02, -2.82840449e-02,  7.94265792e-03,
         4.21435609e-02, -4.19379678e-03, -1.91232786e-02,
        -3.12785469e-02,  1.24685096e-06, -1.04428604e-02,
        -2.19971444e-02, -8.66928250e-02, -1.88502751e-03,
        -2.54772119e-02, -9.72970109e-03,  7.93310180e-02,
        -3.55963036e-02, -3.05334688e-04, -1.12392278e-02,
        -3.88932340e-02,  5.49314320e-02,  1.35207996e-01,
        -8.19147304e-02,  1.18784690e-02, -9.01846774e-0

In [13]:
index.search(svec, k=2)

(array([[1.3799692, 1.3903296]], dtype=float32), array([[3, 2]]))

In [17]:
#first one ie.   array([[1.3799692, 1.3903296]], dtype=float32) ->  distances
#second one ie.  array([[3, 2]])  -> indexes in df

df.head(9) #index 3 and 2 are fashion related like query

text  \
0                                        Meditation and yoga can improve mental health   
1                       Fruits, whole grains and vegetables can control blood pressure   
2                                     These are the latest fashion trends of this week   
3                                   Vibrant colour jeans for male are becoming a trend   
4                                                    The concert starts at 7PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [18]:
distances, indexes= index.search(svec, k=2)
indexes

array([[3, 2]])

In [19]:
df.loc[[3, 2]] #or df.loc[indexes[0]]]

text category
3  Vibrant colour jeans for male are becoming a trend  Fashion
2    These are the latest fashion trends of this week  Fashion